# Generated by Django 5.0 on 2024-02-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_rename_firstname_contactus_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='suggestions',
            new_name='suggestion',
        ),
    ]
